CREATE DATABASE SENAI_PRODUTOS_TARDE;

USE SENAI_PRODUTOS_TARDE;

CREATE TABLE PRODUTOS(

	ID INT  IDENTITY PRIMARY KEY
	,NOME VARCHAR(150) NOT NULL 
	,DESCRICAO VARCHAR(250) NOT NULL
);

INSERT INTO PRODUTOS
VALUES ('PRODUTO_A','UMA BREVE DESCRICAO_A'),('PRODUTO_B','UMA BREVE DESCRICAO_B'),('PRODUTO_C','UMA BREVE DESCRICAO_C')

SELECT *FROM PRODUTOS